FROM centos

RUN cd /etc/yum.repos.d/
RUN sed -i 's/mirrorlist/#mirrorlist/g' /etc/yum.repos.d/CentOS-*
RUN sed -i 's|#baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|g' /etc/yum.repos.d/CentOS-*


# Update system and install essential tools
RUN yum -y update
RUN yum -y install wget curl vim git net-tools passwd man man-pages

# Install Java
RUN yum -y install java

# Install development tools
RUN yum -y groupinstall "Development Tools"

# Install EPEL repository and additional packages
RUN yum -y install epel-release
RUN yum -y install python3 python3-pip
RUN yum -y install openssh-server
RUN yum -y install sudo

CMD /bin/bash

